# Taps
# tap "..."

# Formulae
brew "git"
brew "jq"
brew "fzf"
brew "ripgrep"
brew "chezmoi"

# Casks
cask "android-commandlinetools"
cask "android-platform-tools"
cask "android-studio"
cask "appcleaner"
cask "audacity"
cask "beyond-compare"
cask "bitwarden"
cask "clash-verge-rev"
cask "cryptomator"
cask "dbeaver-community"
cask "font-jetbrains-mono-nerd-font"
cask "hiddenbar"
cask "intellij-idea"
cask "iterm2"
cask "keepassxc"
cask "macfuse"
cask "motrix"
cask "obsidian"
cask "sourcetree"
cask "stats"
cask "swiftformat-for-xcode"
cask "uninstallpkg"
cask "visual-studio-code"