#!/bin/bash
# install.sh - 安装脚本

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_success() { echo -e "${GREEN}✓${NC} $1"; }
print_error() { echo -e "${RED}✗${NC} $1"; }
print_info() { echo -e "${BLUE}➜${NC} $1"; }
print_warning() { echo -e "${YELLOW}⚠${NC} $1"; }

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="$DOTFILES_DIR/backup/$(date +%Y%m%d_%H%M%S)"

echo "================================================"
echo "       Dotfiles 安装脚本"
echo "================================================"
echo ""
print_info "安装目录: $DOTFILES_DIR"
echo ""

# 创建备份目录
mkdir -p "$BACKUP_DIR"

# 备份文件
backup_file() {
    local file=$1
    if [ -f "$file" ] || [ -L "$file" ]; then
        print_info "备份: $file"
        cp -L "$file" "$BACKUP_DIR/$(basename $file)" 2>/dev/null || true
    fi
}

# 添加source引用到配置文件
add_source_line() {
    local config_file=$1
    local source_path=$2
    local marker="# === Dotfiles Configuration ==="
    
    # 确保配置文件存在
    touch "$config_file"
    
    # 检查是否已经添加
    if grep -q "$marker" "$config_file" 2>/dev/null; then
        print_warning "配置已存在于 $config_file"
        return 0
    fi
    
    # 添加引用
    cat >> "$config_file" << EOF

$marker
# Generated by dotfiles installer
# Date: $(date)
if [ -f "$source_path" ]; then
    source "$source_path"
fi
EOF
    print_success "已添加配置引用到 $config_file"
}

# 安装 zsh 配置
install_zsh() {
    print_info "安装 zsh 配置..."
    
    local zshrc="$HOME/.zshrc"
    local loader="$DOTFILES_DIR/config/zshrc.d/loader.zsh"
    
    # 备份现有配置
    backup_file "$zshrc"
    
    # 创建 loader.zsh
    cat > "$loader" << 'EOF'
#!/bin/zsh
# Dotfiles loader - 自动加载所有 zsh 配置

DOTFILES_ZSH_DIR="${0:A:h}"

# 加载所有 .zsh 文件（除了 loader.zsh 本身）
for config_file in "$DOTFILES_ZSH_DIR"/*.zsh; do
    if [[ "$(basename "$config_file")" != "loader.zsh" ]]; then
        source "$config_file"
    fi
done
EOF
    
    # 添加引用到 .zshrc
    add_source_line "$zshrc" "$loader"
    
    print_success "zsh 配置安装完成"
}

# 安装 git 配置
install_git() {
    print_info "安装 git 配置..."
    
    local gitconfig="$HOME/.gitconfig"
    local dotfiles_gitconfig="$DOTFILES_DIR/config/git/gitconfig"
    
    # 备份现有配置
    backup_file "$gitconfig"
    
    # 询问用户信息
    echo ""
    read -p "输入 Git 用户名 (留空保持现有配置): " git_name
    read -p "输入 Git 邮箱 (留空保持现有配置): " git_email
    echo ""
    
    # 添加include引用
    if ! grep -q "\[include\]" "$gitconfig" 2>/dev/null || \
       ! grep -q "path = $dotfiles_gitconfig" "$gitconfig" 2>/dev/null; then
        cat >> "$gitconfig" << EOF

[include]
    path = $dotfiles_gitconfig
EOF
        print_success "已添加配置引用到 .gitconfig"
    else
        print_warning "配置引用已存在于 .gitconfig"
    fi
    
    # 设置用户信息
    if [ -n "$git_name" ]; then
        git config --global user.name "$git_name"
    fi
    if [ -n "$git_email" ]; then
        git config --global user.email "$git_email"
    fi
    
    # 设置全局 gitignore
    git config --global core.excludesfile "$DOTFILES_DIR/config/git/gitignore_global"
    
    print_success "git 配置安装完成"
}

# 配置代理
configure_proxy() {
    print_info "配置代理设置..."
    echo ""
    read -p "输入代理地址 (默认: 127.0.0.1): " proxy_host
    read -p "输入代理端口 (默认: 7890): " proxy_port
    echo ""
    
    proxy_host=${proxy_host:-127.0.0.1}
    proxy_port=${proxy_port:-7890}
    
    # 创建代理配置文件
    local proxy_conf="$DOTFILES_DIR/config/zshrc.d/proxy.conf"
    cat > "$proxy_conf" << EOF
# Proxy configuration
# Generated by install script
PROXY_HOST="$proxy_host"
PROXY_PORT="$proxy_port"
EOF
    
    print_success "代理配置已保存到 proxy.conf"
}

# 保存安装信息
save_install_info() {
    cat > "$DOTFILES_DIR/.install_info" << EOF
INSTALL_DATE=$(date)
BACKUP_DIR=$BACKUP_DIR
DOTFILES_DIR=$DOTFILES_DIR
EOF
}

# 主安装流程
main() {
    # 检查 zsh
    if ! command -v zsh &> /dev/null; then
        print_error "未找到 zsh，请先安装 zsh"
        exit 1
    fi
    
    # 询问安装选项
    echo "请选择要安装的配置："
    echo "1) 全部安装"
    echo "2) 仅 zsh 配置"
    echo "3) 仅 git 配置"
    echo "4) 自定义选择"
    read -p "请输入选项 (1-4): " choice
    echo ""
    
    case $choice in
        1)
            configure_proxy
            install_zsh
            install_git
            ;;
        2)
            configure_proxy
            install_zsh
            ;;
        3)
            install_git
            ;;
        4)
            read -p "安装 zsh 配置? (y/n): " install_zsh_choice
            if [[ $install_zsh_choice =~ ^[Yy]$ ]]; then
                configure_proxy
                install_zsh
            fi
            
            read -p "安装 git 配置? (y/n): " install_git_choice
            if [[ $install_git_choice =~ ^[Yy]$ ]]; then
                install_git
            fi
            ;;
        *)
            print_error "无效选项"
            exit 1
            ;;
    esac
    
    # 保存安装信息
    save_install_info
    
    echo ""
    echo "================================================"
    print_success "安装完成！"
    echo "================================================"
    echo ""
    print_info "备份文件保存在: $BACKUP_DIR"
    echo ""
    echo "请运行以下命令使配置生效："
    echo "  ${GREEN}source ~/.zshrc${NC}"
    echo ""
    echo "常用命令："
    echo "  ${BLUE}pon/proxy_on${NC}     - 开启代理"
    echo "  ${BLUE}poff/proxy_off${NC}   - 关闭代理"
    echo "  ${BLUE}pst/proxy_status${NC} - 查看代理状态"
    echo ""
    echo "卸载："
    echo "  ${YELLOW}./uninstall.sh${NC}"
    echo ""
}

main
